export const ASYNC_REQUEST_BASE_KEYS = [
    "board:member:edit:role",
    "board:member:delete",
    "board:shareoffer:create",
    "board:sharelink:create",
    "board:sharelink:revoke",
    "board:member:fetch",
    "board:edit:visibility",
    "board:edit:background:color",
    "board:edit:background:image",
    "watch:fetch",
    "watch:add:board",
    "watch:add:list",
    "watch:add:card",
    "watch:patch:board",
    "watch:patch:list",
    "watch:patch:card",
    "userboard:edit:starred",
    "board:close",
    "board:label:create",
    "board:label:edit",
    "board:label:delete",
    "card:label:add",
    "card:label:remove",
    "board:archive:fetch",
    "board:archive:list:restore",
    "board:archive:card:restore",
    "board:archive:list:purge",
    "board:archive:card:purge",
    "list:create",
    "list:copy:bulk",
    "list:move",
    "list:mirror",
    "list:detach",
    "list:edit:title",
    "list:edit:props",
    "list:edit:access",
    "listcard:rootboard:fetch",
    "card:create",
    "card:delete",
    "card:edit:details",
    "card:edit:description",
    "card:edit:done",
    "card:edit:title",
    "card:edit:title:inline",
    "card:edit:title:cardmenu",
    "card:edit:dates",

    "card:edit:dates:remove",
    "card:edit:dates:add",
    "card:edit:dates:editmodal",
    "card:edit:dates:cardmenu",
    "card:edit:dates:remove:editmodal",
    "card:edit:dates:remove:cardmenu",
    "card:edit:dates:add:editmodal",
    "card:edit:dates:add:cardmenu",

    "card:edit:props",
    "card:move",
    "card:move:bulk",
    "card:detach:bulk",
    "card:mirror",
    "card:copy",
    "card:member:add",
    "card:member:remove",

    "card:mirror:fetch",

    "checklist:create",
    "checklist:clone",
    "checklist:delete",
    "checklist:edit",
    "checklist:move",
    "checklist:entry:create",
    "checklist:entry:edit",
    "checklist:entry:convert",
    "checklist:entry:delete",
    "checklist:entry:move",
    "checklist:entry:crossmove",
    "checklist:entry:member:add",
    "checklist:entry:member:remove",
    "subscription:checkout",
    "subscription:cancel",
    "subscription:resume",
    "subscription:suspension:boards:save",
    "subscription:suspension:members:save",
    "workspace:boards:fetch:all",
    "workspace:boards:fetch",
    "workspace:create",
    "inbox:card:move:board:list",
    "inbox:card:copy:board:list",
    "inbox:card:detatch",
    "workspace:board:create",
    "board:read:detail",
    "shareoffer:respond",
    "shareoffer:revoke",
] as const;

export type AsyncRequestBaseKey = typeof ASYNC_REQUEST_BASE_KEYS[number];

/** A known base key, or a composite key starting with a known base: "base:instanceID" */
export type AsyncRequestKey =
    | AsyncRequestBaseKey
    | `${AsyncRequestBaseKey}:${string}`