package EventRegistry

type AuditTemplateKey string

const (
	AuditTemplateLegacyEvent AuditTemplateKey = "audit.legacy.event"

	AuditTemplateCardCreated  AuditTemplateKey = "audit.card.created"
	AuditTemplateCardPatched  AuditTemplateKey = "audit.card.patched"
	AuditTemplateCardMirrored AuditTemplateKey = "audit.card.mirrored"

	AuditTemplateLabelCreated     AuditTemplateKey = "audit.label.created"
	AuditTemplateLabelDeleted     AuditTemplateKey = "audit.label.deleted"
	AuditTemplateLabelPatched     AuditTemplateKey = "audit.label.patched"
	AuditTemplateCardLabelAdded   AuditTemplateKey = "audit.card.label.added"
	AuditTemplateCardLabelRemoved AuditTemplateKey = "audit.card.label.removed"

	AuditTemplateCardMemberAdded       AuditTemplateKey = "audit.card.member.added"
	AuditTemplateCardMemberRemoved     AuditTemplateKey = "audit.card.member.removed"
	AuditTemplateCardMemberAddedSelf   AuditTemplateKey = "audit.card.member.added.self"
	AuditTemplateCardMemberRemovedSelf AuditTemplateKey = "audit.card.member.removed.self"

	AuditTemplateCardCommentCreated AuditTemplateKey = "audit.card_comment.created"
	AuditTemplateCardCommentDeleted AuditTemplateKey = "audit.card_comment.deleted"
	AuditTemplateCardCommentEdited  AuditTemplateKey = "audit.card_comment.edited"
	AuditTemplateBoardPatched       AuditTemplateKey = "audit.board.patched"
	AuditTemplateListPatched        AuditTemplateKey = "audit.list.patched"

	AuditTemplateChecklistCreated                AuditTemplateKey = "audit.checklist.created"
	AuditTemplateChecklistPatched                AuditTemplateKey = "audit.checklist.patched"
	AuditTemplateChecklistDeleted                AuditTemplateKey = "audit.checklist.deleted"
	AuditTemplateChecklistMoved                  AuditTemplateKey = "audit.checklist.moved"
	AuditTemplateChecklistEntryCreated           AuditTemplateKey = "audit.checklist.entry.created"
	AuditTemplateChecklistEntryPatched           AuditTemplateKey = "audit.checklist.entry.patched"
	AuditTemplateChecklistEntryDeleted           AuditTemplateKey = "audit.checklist.entry.deleted"
	AuditTemplateChecklistEntryMoved             AuditTemplateKey = "audit.checklist.entry.moved"
	AuditTemplateChecklistEntryMemberAdded       AuditTemplateKey = "audit.checklist.entry.member.added"
	AuditTemplateChecklistEntryMemberRemoved     AuditTemplateKey = "audit.checklist.entry.member.removed"
	AuditTemplateChecklistEntryMemberAddedSelf   AuditTemplateKey = "audit.checklist.entry.member.added.self"
	AuditTemplateChecklistEntryMemberRemovedSelf AuditTemplateKey = "audit.checklist.entry.member.removed.self"

	AuditTemplateWorkspaceBoardCreated             AuditTemplateKey = "audit.workspace.board.created"
	AuditTemplateWorkspaceBoardClosed              AuditTemplateKey = "audit.workspace.board.closed"
	AuditTemplateWorkspaceBoardRestored            AuditTemplateKey = "audit.workspace.board.restored"
	AuditTemplateWorkspaceBoardPurged              AuditTemplateKey = "audit.workspace.board.purged"
	AuditTemplateWorkspacePatched                  AuditTemplateKey = "audit.workspace.patched"
	AuditTemplateWorkspaceMemberRoleChanged        AuditTemplateKey = "audit.workspace.member.role.changed"
	AuditTemplateWorkspaceMemberRoleChangedSelf    AuditTemplateKey = "audit.workspace.member.role.changed.self"
	AuditTemplateWorkspaceMemberRemoved            AuditTemplateKey = "audit.workspace.member.removed"
	AuditTemplateWorkspaceMemberRemovedSelf        AuditTemplateKey = "audit.workspace.member.removed.self"
	AuditTemplateBoardMemberRemoved                AuditTemplateKey = "audit.board.member.removed"
	AuditTemplateBoardMemberRemovedSelf            AuditTemplateKey = "audit.board.member.removed.self"
	AuditTemplateBoardMemberRoleChanged            AuditTemplateKey = "audit.board.member.role.changed"
	AuditTemplateBoardMemberRoleChangedSelf        AuditTemplateKey = "audit.board.member.role.changed.self"
	AuditTemplateWorkspaceShareOfferCreated        AuditTemplateKey = "audit.workspace.shareoffer.created"
	AuditTemplateWorkspaceShareOfferInviteAccepted AuditTemplateKey = "audit.workspace.shareoffer.invite.accepted"
	AuditTemplateWorkspaceShareOfferInviteRejected AuditTemplateKey = "audit.workspace.shareoffer.invite.rejected"
	AuditTemplateWorkspaceShareOfferInviteRevoked  AuditTemplateKey = "audit.workspace.shareoffer.invite.revoked"
	AuditTemplateWorkspaceAccessClaimed            AuditTemplateKey = "audit.workspace.access.claimed"
	AuditTemplateBoardShareRequestCreated          AuditTemplateKey = "audit.board.shareoffer.request.created"
	AuditTemplateBoardShareRequestAccepted         AuditTemplateKey = "audit.board.shareoffer.request.accepted"
	AuditTemplateBoardShareRequestRejected         AuditTemplateKey = "audit.board.shareoffer.request.rejected"
	AuditTemplateBoardAccessClaimed                AuditTemplateKey = "audit.board.access.claimed"

	AuditTemplateBoardListCreated           AuditTemplateKey = "audit.board.list.created"
	AuditTemplateBoardListDetached          AuditTemplateKey = "audit.board.list.detached"
	AuditTemplateBoardListRestored          AuditTemplateKey = "audit.board.list.restored"
	AuditTemplateBoardListPurged            AuditTemplateKey = "audit.board.list.purged"
	AuditTemplateBoardListMoved             AuditTemplateKey = "audit.board.list.moved"
	AuditTemplateBoardListPatched           AuditTemplateKey = "audit.board.list.patched"
	AuditTemplateBoardListMirrored          AuditTemplateKey = "audit.board.list.mirrored"
	AuditTemplateBoardListMirroredTarget    AuditTemplateKey = "audit.board.list.mirrored.target"
	AuditTemplateBoardListMirroredSource    AuditTemplateKey = "audit.board.list.mirrored.source"
	AuditTemplateBoardListCardMoved         AuditTemplateKey = "audit.board.listcard.moved"
	AuditTemplateBoardListCardRestored      AuditTemplateKey = "audit.board.listcard.restored"
	AuditTemplateBoardListCardPurged        AuditTemplateKey = "audit.board.listcard.purged"
	AuditTemplateBoardListCardsBulkMoved    AuditTemplateKey = "audit.board.listcards.bulkmoved"
	AuditTemplateBoardListCardDetached      AuditTemplateKey = "audit.board.listcard.detached"
	AuditTemplateBoardListCardsBulkDetached AuditTemplateKey = "audit.board.listcards.bulkdetached"
	AuditTemplateBoardListCardDetatched     AuditTemplateKey = "audit.board.listcard.detatched"

	AuditTemplateBoardShareLinkCreated     AuditTemplateKey = "audit.board.sharelink.created"
	AuditTemplateBoardShareLinkRevoked     AuditTemplateKey = "audit.board.sharelink.revoked"
	AuditTemplateWorkspaceShareLinkCreated AuditTemplateKey = "audit.workspace.sharelink.created"
	AuditTemplateWorkspaceShareLinkRevoked AuditTemplateKey = "audit.workspace.sharelink.revoked"

	AuditTemplateWorkspaceSubscriptionCreated  AuditTemplateKey = "audit.workspace.subscription.created"
	AuditTemplateWorkspaceSubscriptionUpdated  AuditTemplateKey = "audit.workspace.subscription.updated"
	AuditTemplateWorkspaceSubscriptionCanceled AuditTemplateKey = "audit.workspace.subscription.canceled"
)
